apiVersion: apps/v1
kind: Deployment
metadata:
  name: shibuya-apiserver-{{ .Values.context }}
  labels:
    {{- range .Values.apiserver.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- range .Values.apiserver.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range .Values.apiserver.labels }}
        {{.key }}: {{.value }}
        {{- end }}
      {{- if .Values.apiserver.annotations }}
      annotations:
        {{- range .Values.apiserver.annotations }}
        {{.key }}: {{.value }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccount: shibuya
      {{- if .Values.image_pull_secrets }}
      imagePullSecrets:
        {{- range .Values.image_pull_secrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
      - image: {{ .Values.repository }}{{ .Values.apiserver.image.name }}:{{ .Values.tag }}
        name: shibuya
        resources:
          requests:
            cpu: {{ .Values.apiserver.resources.requests.cpu | quote }}
            memory: {{ .Values.apiserver.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.apiserver.resources.limits.cpu | quote }}
            memory: {{ .Values.apiserver.resources.limits.memory | quote }}

        env:
        {{- range .Values.apiserver.envvars }}
        - name: {{ .key | quote }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.runtime.auth_config.oauth_logins.google  }}
        - name: google_client_id
          valueFrom:
            secretKeyRef:
              name: google-oauth2
              key: client_id
        - name: google_client_secret
          valueFrom:
            secretKeyRef:
              name: google-oauth2
              key: client_secret
        {{- end }}
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: shibuya-ca
          mountPath: "/tls"
          readOnly: true
        - name: shibuya-config
          mountPath: /config.json
          subPath: config.json
        {{- if not .Values.runtime.executors.in_cluster }}
        - name: kubeconfig-volume
          mountPath: /root/.kube/config
          subPath: config
        {{- end }}
        {{- if eq .Values.runtime.object_storage.provider "gcp" }}
        - name: shibuya-gcp-auth
          mountPath: /auth/shibuya-gcp.json
          subPath: shibuya-gcp.json
        {{- end }}
      volumes:
      - name: shibuya-ca
        secret:
          secretName: shibuya-ca-crt
      - name: shibuya-config
        configMap:
          name: shibuya-config-{{ .Values.context }}
      {{- if not .Values.runtime.executors.in_cluster }}
      - name: kubeconfig-volume
        configMap:
          defaultMode: 420
          name: shibuya-token-{{ .Values.cluster_name }}
      {{- end }}
      {{- if eq .Values.runtime.object_storage.provider "gcp" }}
      - name: shibuya-gcp-auth
        secret:
          secretName: shibuya-auth-keys-gcp
      {{- end }}
      {{- if .Values.runtime.auth_config.enable_google_login  }}
      - name: google-oauth2
        secret:
          secretName: google-oauth2
      {{- end }}

