FROM gcr.io/shibuya-214807/golang:1.13.6-stretch AS builder


WORKDIR /go/src/shibuya/controller/worker

ENV GO111MODULE on
# ADD go.mod .
# ADD go.sum .
#ENV GOPROXY=https://goproxy.io
#RUN go mod download

COPY . /go/src/shibuya

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/worker

# Use only binaries from above image for running the app
FROM gcr.io/shibuya-214807/ubuntu:18.04

COPY --from=builder /go/bin/worker /usr/local/bin/worker

CMD ["worker"]