apiVersion: v1
kind: ServiceAccount
metadata:
  name: shibuya-coordinator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shibuya-coordinator
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - namespaces
      - pods
    verbs:
      - list
  - apiGroups:
    - "apps"
    resources:
      - statefulsets
    verbs:
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shibuya-coordinator
subjects:
- kind: ServiceAccount
  name:  shibuya-coordinator
roleRef:
  kind: Role
  name: shibuya-coordinator
  apiGroup: rbac.authorization.k8s.io
