apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: engine
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      kind: executor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scraper
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      kind: scraper
