apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shibuya
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - endpoints
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - ""
  - rbac.authorization.k8s.io
  resources:
  - deployments
  - statefulsets
  - serviceaccounts
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - delete
  - update
  - patch
  - deletecollection
- apiGroups:
  - ""
  - "extensions"
  resources:
  - services
  - configmaps
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  - ingressclasses
  verbs:
  - "*"
- apiGroups:
  - "extensions"
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch