apiVersion: v1
kind: ServiceAccount
metadata:
  name: shibuya-scraper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shibuya-scraper
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shibuya-scraper
subjects:
- kind: ServiceAccount
  name:  shibuya-scraper
roleRef:
  kind: Role
  name: shibuya-scraper
  apiGroup: rbac.authorization.k8s.io
