apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  serviceName: worker
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: shibuya:worker
        name: worker
        env:
        - name: ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
#