name: Build the shibuya charts

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-20.04
    steps:
    - uses: googleapis/release-please-action@v4
      id: create_release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: helm
        path: shibuya/install
